import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import Image from 'next/image'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section >
        <nav className="bg-blue-600 shadow-md">
      <div className="max-w-screen-xl mx-auto p-4 flex flex-wrap items-center justify-between">
      <Link href="" className="flex items-center space-x-3">
          <Image src="/logo3.svg" alt="Flowbite Logo" width={224} height={32} />
        </Link>
        <div className="w-full md:block md:w-auto" id="navbar-default">
          <ul className="font-medium flex flex-col p-4 md:p-0 mt-4 bg-blue-500 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-transparent">
            <li>
              <Link href="#" className="block py-2 px-3 text-white rounded-md hover:bg-blue-700 md:hover:bg-transparent md:p-0">
                Home
              </Link>
            </li>
            <li>
              <Link href="#" className="block py-2 px-3 text-white rounded-md hover:bg-blue-700 md:hover:bg-transparent md:p-0">
                About
              </Link>
            </li>
            <li>
              <Link href="#" className="block py-2 px-3 text-white rounded-md hover:bg-blue-700 md:hover:bg-transparent md:p-0">
                Services
              </Link>
            </li>
            <li>
              <Link href="#" className="block py-2 px-3 text-white rounded-md hover:bg-blue-700 md:hover:bg-transparent md:p-0">
                Contact
              </Link>
            </li>
          </ul>
        </div>
      </div>
    </nav>

        </section>
        {children}
        <section>


          <footer className="bg-white dark:bg-gray-900">
            <div className="mx-auto w-full max-w-screen-xl p-4 py-6 lg:py-8">
              <div className="md:flex md:justify-between">
                <div className="grid grid-cols-2 gap-8 sm:gap-6 sm:grid-cols-3">
                  <div>
                    <h2 className="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Resources</h2>
                    <ul className="text-gray-500 dark:text-gray-400 font-medium">
                      <li className="mb-4">
                        <a href="https://flowbite.com/" className="hover:underline">Flowbite</a>
                      </li>
                      <li>
                        <a href="https://tailwindcss.com/" className="hover:underline">Tailwind CSS</a>
                      </li>
                    </ul>
                  </div>
                  
                  <div>
                    <h2 className="mb-6 text-sm font-semibold text-gray-900 uppercase dark:text-white">Legal</h2>
                    <ul className="text-gray-500 dark:text-gray-400 font-medium">
                      <li className="mb-4">
                        <a href="#" className="hover:underline">Privacy Policy</a>
                      </li>
                      <li>
                        <a href="#" className="hover:underline">Terms &amp; Conditions</a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <hr className="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8" />
              <div className="sm:flex sm:items-center sm:justify-between">
                <span className="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2023 <a href="https://flowbite.com/" className="hover:underline">Flowbite™</a>. All Rights Reserved.
                </span>
               
              </div>
            </div>
          </footer>

        </section>
      </body>
    </html>
  );
}
